---
workspace:
  base: /go
  path: src/github.com/supervised-io/catalog

pipeline:
  dinv-build:
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    image: docker:latest
    pull: true
    commands:
      - docker ps
      - apk add --update bash git
      - dinv/ci.sh
    when:
      branch: master
      repo: vmware/vic-product

services:
  dind:
    image: docker:dind
    privileged: true
    pull: true
