---
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  dinv-build:
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    image: docker:latest
    pull: true
    commands:
      - docker ps
      - apk add --update bash git
      - dinv/ci.sh build
    when:
      branch: master
      repo: vmware/vic-product
      event: [push, pull_request, tag, deployment]

  dinv-push:
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    image: docker:latest
    pull: true
    commands:
      - docker ps
      - apk add --update bash git
      - dinv/ci.sh push
    when:
      branch: master
      repo: vmware/vic-product
      event: [push, tag, deployment]

services:
  dind:
    image: docker:dind
    privileged: true
    pull: true
